//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Todo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub time_estimate: i32,
    pub completed_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::todo_time_entry::Entity")]
    TodoTimeEntry,
    #[sea_orm(has_many = "super::work_session::Entity")]
    WorkSession,
}

impl Related<super::todo_time_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodoTimeEntry.def()
    }
}

impl Related<super::work_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
