//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "window_positions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub window_key: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub desktop_arrangement: String,
    pub window_position_x: i32,
    pub window_position_y: i32,
    pub window_size_w: i32,
    pub window_size_h: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
