(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this);function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&r(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.g=h;r(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=t[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&r(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function da(a){return a.raw=a}function w(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.S=b.prototype}function ma(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.u=0;this.j=null}function na(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}ma.prototype.s=function(a){this.i=a};function oa(a,b){a.j={Y:b,Z:!0};a.g=a.u}
ma.prototype.return=function(a){this.j={return:a};this.g=this.u};function y(a,b,c){a.g=c;return{value:b}}function pa(a){this.g=new ma;this.h=a}function qa(a,b){na(a.g);var c=a.g.h;if(c)return ra(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return z(a)}
function ra(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var h=e.value}catch(f){return a.g.h=null,oa(a.g,f),z(a)}a.g.h=null;d.call(a.g,h);return z(a)}function z(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,oa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.Z)throw b.Y;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function sa(a){this.next=function(b){na(a.g);a.g.h?b=ra(a,a.g.h.next,b,a.g.s):(a.g.s(b),b=z(a));return b};this.throw=function(b){na(a.g);a.g.h?b=ra(a,a.g.h["throw"],b,a.g.s):(oa(a.g,b),b=z(a));return b};this.return=function(b){return qa(a,b)};this[Symbol.iterator]=function(){return this}}function ta(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function A(a){return ta(new sa(new pa(a)))}function ua(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(f){this.g=0;this.i=void 0;this.h=[];this.u=!1;var g=this.j();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(f)};var e=t.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.F),reject:f(this.l)}};b.prototype.F=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.H(f);else{a:switch(typeof f){case "object":var g=null!=f;break a;case "function":g=!0;break a;default:g=!1}g?this.B(f):this.s(f)}};
b.prototype.B=function(f){var g=void 0;try{g=f.then}catch(k){this.l(k);return}"function"==typeof g?this.I(g,f):this.s(f)};b.prototype.l=function(f){this.A(2,f)};b.prototype.s=function(f){this.A(1,f)};b.prototype.A=function(f,g){if(0!=this.g)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.g);this.g=f;this.i=g;2===this.g&&this.G();this.C()};b.prototype.G=function(){var f=this;e(function(){if(f.D()){var g=t.console;"undefined"!==typeof g&&g.error(f.i)}},1)};b.prototype.D=
function(){if(this.u)return!1;var f=t.CustomEvent,g=t.Event,k=t.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof g?f=new g("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.C=function(){if(null!=this.h){for(var f=0;f<this.h.length;++f)h.h(this.h[f]);this.h=null}};var h=new c;b.prototype.H=
function(f){var g=this.j();f.K(g.resolve,g.reject)};b.prototype.I=function(f,g){var k=this.j();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(p,v){return"function"==typeof p?function(J){try{l(p(J))}catch(x){m(x)}}:v}var l,m,q=new b(function(p,v){l=p;m=v});this.K(k(f,l),k(g,m));return q};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.K=function(f,g){function k(){switch(l.g){case 1:f(l.i);break;case 2:g(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;null==this.h?h.h(k):this.h.push(k);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=w(f),m=l.next();!m.done;m=l.next())d(m.value).K(g,k)})};b.all=function(f){var g=w(f),k=g.next();return k.done?d([]):new b(function(l,m){function q(J){return function(x){p[J]=x;v--;0==v&&l(p)}}var p=[],v=0;do p.push(void 0),v++,d(k.value).K(q(p.length-1),m),k=g.next();while(!k.done)})};return b});
u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});function B(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
u("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=w(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!B(k,f)){var l=new c;r(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(q){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!B(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&B(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&B(k,
f)&&B(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&B(k,f)&&B(k[f],this.g)?delete k[f][this.g]:!1};return b});
u("Map",function(a){function b(){var g={};return g.v=g.next=g.head=g}function c(g,k){var l=g[1];return ca(function(){if(l){for(;l.head!=g[1];)l=l.v;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;"object"==l||"function"==l?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&B(g[0],l))for(g=0;g<m.length;g++){var q=m[g];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:g,m:q}}return{id:l,
list:m,index:-1,m:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=w(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a(w([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(q){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.m?l.m.value=k:(l.m={next:this[1],v:this[1].v,head:this[1],key:g,value:k},l.list.push(l.m),this[1].v.next=l.m,this[1].v=l.m,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.m&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.m.v.next=g.m.next,g.m.next.v=g.m.v,g.m.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].v=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).m};e.prototype.get=function(g){return(g=d(this,g).m)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});u("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)B(b,d)&&c.push(b[d]);return c}});u("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
u("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
function va(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.entries",function(a){return a?a:function(){return va(this,function(b,c){return[b,c]})}});
u("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],h="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof h){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});u("Array.prototype.keys",function(a){return a?a:function(){return va(this,function(b){return b})}});
u("Array.prototype.values",function(a){return a?a:function(){return va(this,function(b,c){return c})}});var wa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)B(d,e)&&(a[e]=d[e])}return a};u("Object.assign",function(a){return a||wa});u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)B(b,d)&&c.push([d,b[d]]);return c}});
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var xa=xa||{},C=this||self;function ya(a,b){a=a.split(".");b=b||C;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}
function za(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function Aa(a){var b=za(a);return"array"==b||"object"==b&&"number"==typeof a.length}function Ba(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ca(a,b,c){return a.call.apply(a.bind,arguments)}
function Da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function D(a,b,c){D=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Ca:Da;return D.apply(null,arguments)}
function Ea(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ma=function(d,e,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,f)}}function Fa(a){return a};var Ga;var Ia,Ja=ya("CLOSURE_FLAGS"),Ka=Ja&&Ja[610401301];Ia=null!=Ka?Ka:!1;function La(){var a=C.navigator;return a&&(a=a.userAgent)?a:""}var E,Ma=C.navigator;E=Ma?Ma.userAgentData||null:null;function Na(a){return Ia?E?E.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function F(a){return-1!=La().indexOf(a)};function G(){return Ia?!!E&&0<E.brands.length:!1}function Oa(){return G()?Na("Chromium"):(F("Chrome")||F("CriOS"))&&!(G()?0:F("Edge"))||F("Silk")};var Pa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Qa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Ra(a,b){b=Pa(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}function Sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ta=G()?!1:F("Trident")||F("MSIE"),Ua=-1!=La().toLowerCase().indexOf("webkit")&&!F("Edge")&&F("Mobile");!F("Android")||Oa();Oa();F("Safari")&&(Oa()||(G()?0:F("Coast"))||(G()?0:F("Opera"))||(G()?0:F("Edge"))||(G()?Na("Microsoft Edge"):F("Edg/"))||G()&&Na("Opera"));var Va={},Wa=null;var Xa="undefined"!==typeof Uint8Array,Ya=!Ta&&"function"===typeof btoa;var H="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0,Za=Math.max,$a=Za.apply,ab=Object.values({ia:1,ha:2,ga:4,ka:8,ja:16,ca:32,la:64,ea:128,da:256,fa:512}),bb;if(ab instanceof Array)bb=ab;else{for(var cb=w(ab),db,eb=[];!(db=cb.next()).done;)eb.push(db.value);bb=eb}$a.call(Za,Math,bb);var fb=H?function(a,b){a[H]|=b}:function(a,b){void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};
function gb(a){var b=I(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=Array.prototype.slice.call(a)),K(a,b|1))}var I=H?function(a){return a[H]|0}:function(a){return a.g|0},L=H?function(a){return a[H]}:function(a){return a.g},K=H?function(a,b){a[H]=b}:function(a,b){void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function hb(){var a=[];fb(a,1);return a}function ib(a,b){K(b,(a|0)&-51)}function jb(a,b){K(b,(a|18)&-41)}
function kb(a){a=a>>10&1023;return 0===a?536870912:a};var lb={};function M(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var N,mb=[];K(mb,23);N=Object.freeze(mb);function nb(a){return a.displayName||a.name||"unknown type name"};var ob;function pb(a,b){ob=b;a=new a(b);ob=void 0;return a}
function qb(a,b,c){null==a&&(a=ob);ob=void 0;if(null==a){var d=48;c?(a=[c],d|=256):a=[];b&&(d=d&-1047553|(b&1023)<<10)}else{if(!Array.isArray(a))throw Error();d=I(a);if(d&32)return a;d|=32;if(c&&(d|=256,c!==a[0]))throw Error();a:{c=a;var e=c.length;if(e){var h=e-1,f=c[h];if(M(f)){d|=128;b=(d>>8&1)-1;e=h-b;1024<=e&&(rb(c,b,f),e=1023);d=d&-1047553|(e&1023)<<10;break a}}b&&(f=(d>>8&1)-1,b=Math.max(b,e-f),1024<b&&(rb(c,f,{}),d|=128,b=1023),d=d&-1047553|(b&1023)<<10)}}K(a,d);return a}
function rb(a,b,c){for(var d=1023+b,e=a.length,h=d;h<e;h++){var f=a[h];null!=f&&f!==c&&(c[h-b]=f)}a.length=d+1;a[d]=c};function sb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&Xa&&null!=a&&a instanceof Uint8Array){if(Ya){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!Wa){Wa={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=","+/","-_=","-_.","-_"];for(var e=
0;5>e;e++){var h=c.concat(d[e].split(""));Va[e]=h;for(var f=0;f<h.length;f++){var g=h[f];void 0===Wa[g]&&(Wa[g]=f)}}}b=Va[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=h=0;h<a.length-2;h+=3){var k=a[h],l=a[h+1];g=a[h+2];f=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[e++]=""+f+k+l+g}f=0;g=d;switch(a.length-h){case 2:f=a[h+1],g=b[(f&15)<<2]||d;case 1:a=a[h],c[e]=""+b[a>>2]+b[(a&3)<<4|f>>4]+g+d}a=c.join("")}return a}}return a};function tb(a,b,c){a=Array.prototype.slice.call(a);var d=a.length,e=b&128?a[d-1]:void 0;d+=e?-1:0;for(b=b&256?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(var h in e)b[h]=c(e[h])}return a}function ub(a,b,c,d,e,h){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&I(a)&1?void 0:h&&I(a)&2?a:vb(a,b,c,void 0!==d,e,h);else if(M(a)){var f={},g;for(g in a)f[g]=ub(a[g],b,c,d,e,h);a=f}else a=b(a,d);return a}}
function vb(a,b,c,d,e,h){var f=d||c?I(a):0;d=d?!!(f&16):void 0;a=Array.prototype.slice.call(a);for(var g=0;g<a.length;g++)a[g]=ub(a[g],b,c,d,e,h);c&&c(f,a);return a}function wb(a){return a.R===lb?a.toJSON():sb(a)};function xb(a,b,c){c=void 0===c?jb:c;if(null!=a){if(Xa&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=I(a);if(d&2)return a;if(b&&!(d&32)&&(d&16||0===d))return K(a,d|18),a;a=vb(a,xb,d&4?jb:c,!0,!1,!0);b=I(a);b&4&&b&2&&Object.freeze(a);return a}a.R===lb&&(b=a.o,c=L(b),a=c&2?a:yb(a,b,c,!0));return a}}function yb(a,b,c,d){var e=d||c&2?jb:ib,h=!!(c&16);b=tb(b,c,function(f){return xb(f,h,e)});fb(b,16|(d?2:0));return pb(a.constructor,b)};function zb(a,b,c,d){if(-1===c)return null;if(c>=kb(b)){if(b&128)return a[a.length-1][c]}else{var e=a.length;if(d&&b&128&&(d=a[e-1][c],null!=d))return d;b=c+((b>>8&1)-1);if(b<e)return a[b]}}function Ab(a,b,c,d,e){var h=kb(b);if(c>=h||e){e=b;if(b&128)h=a[a.length-1];else{if(null==d)return;h=a[h+((b>>8&1)-1)]={};e|=128}h[c]=d;e&=-513;e!==b&&K(a,e)}else a[c+((b>>8&1)-1)]=d,b&128&&(d=a[a.length-1],c in d&&delete d[c]),b&512&&K(a,b&-513)}
function O(a,b,c){if(null!=c){if("boolean"!==typeof c)throw Error("Expected boolean but got "+za(c)+": "+c);c=!!c}var d=a.o,e=L(d);if(e&2)throw Error();Ab(d,e,b,!1!==c?c:void 0);return a}function P(a,b){a=a.o;b=zb(a,L(a),b);b=null==b?b:"boolean"===typeof b||"number"===typeof b?!!b:void 0;return null!=b?b:!1};function Q(a,b,c){this.o=qb(a,b,c)}Q.prototype.toJSON=function(){var a=vb(this.o,wb,void 0,void 0,!1,!1);return Bb(this,a,!0)};Q.prototype.R=lb;Q.prototype.toString=function(){return Bb(this,this.o,!1).toString()};
function Bb(a,b,c){var d=a.constructor.na,e=kb(L(c?a.o:b)),h=!1;if(d){if(!c){b=Array.prototype.slice.call(b);var f;if(b.length&&M(f=b[b.length-1]))for(h=0;h<d.length;h++)if(d[h]>=e){Object.assign(b[b.length-1]={},f);break}h=!0}e=b;c=!c;f=L(a.o);a=kb(f);f=(f>>8&1)-1;for(var g,k,l=0;l<d.length;l++)if(k=d[l],k<a){k+=f;var m=e[k];null==m?e[k]=c?N:hb():c&&m!==N&&gb(m)}else g||(m=void 0,e.length&&M(m=e[e.length-1])?g=m:e.push(g={})),m=g[k],null==g[k]?g[k]=c?N:hb():c&&m!==N&&gb(m)}d=b.length;if(!d)return b;
var q;if(M(g=b[d-1])){a:{var p=g;e={};c=!1;for(var v in p)a=p[v],Array.isArray(a)&&a!=a&&(c=!0),null!=a?e[v]=a:c=!0;if(c){for(var J in e){p=e;break a}p=null}}p!=g&&(q=!0);d--}for(;0<d;d--){g=b[d-1];if(null!=g)break;var x=!0}if(!q&&!x)return b;var Ha;h?Ha=b:Ha=Array.prototype.slice.call(b,0,d);b=Ha;h&&(b.length=d);p&&b.push(p);return b};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var Cb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Db(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Cb.length;h++)c=Cb[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Eb;function Fb(a){this.g=a}Fb.prototype.toString=function(){return this.g+""};var Gb={};function Hb(a){if(void 0===Eb){var b=null;var c=C.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("uf-api#html",{createHTML:Fa,createScript:Fa,createScriptURL:Fa})}catch(d){C.console&&C.console.error(d.message)}Eb=b}else Eb=b}a=(b=Eb)?b.createScriptURL(a):a;return new Fb(a,Gb)};function R(a){this.g=a}R.prototype.toString=function(){return this.g.toString()};var Ib={},Jb=new R("about:invalid#zClosurez",Ib);var Kb=/^[\w+/_-]+[=]{0,2}$/;function Lb(a){a=(a||C).document;return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&Kb.test(a)?a:"":""};function Mb(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var h=c[e];if(!Aa(h)||Ba(h)&&0<h.nodeType)d(h);else{a:{if(h&&"number"==typeof h.length){if(Ba(h)){var f="function"==typeof h.item||"string"==typeof h.item;break a}if("function"===typeof h){f="function"==typeof h.item;break a}}f=!1}Qa(f?Sa(h):h,d)}}}function Nb(a){var b="SCRIPT";"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function Ob(a){this.g=a||C.document||document}Ob.prototype.append=function(a,b){Mb(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments)};function S(){this.l=this.l;this.u=this.u}S.prototype.l=!1;S.prototype.isDisposed=function(){return this.l};S.prototype.J=function(){if(this.u)for(;this.u.length;)this.u.shift()()};function Pb(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};var Qb="closure_listenable_"+(1E6*Math.random()|0);var Rb=0;function Sb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.P=e;this.key=++Rb;this.L=this.O=!1}function Tb(a){a.L=!0;a.listener=null;a.proxy=null;a.src=null;a.P=null};function Ub(a){this.src=a;this.g={};this.h=0}Ub.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var f=Vb(a,b,d,e);-1<f?(b=a[f],c||(b.O=!1)):(b=new Sb(b,this.src,h,!!d,e),b.O=c,a.push(b));return b};function Wb(a,b){var c=b.type;c in a.g&&Ra(a.g[c],b)&&(Tb(b),0==a.g[c].length&&(delete a.g[c],a.h--))}function Vb(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.L&&h.listener==b&&h.capture==!!c&&h.P==d)return e}return-1};var Xb="closure_lm_"+(1E6*Math.random()|0),Yb={},Zb=0;
function $b(a,b,c,d,e){if(Array.isArray(b))for(var h=0;h<b.length;h++)$b(a,b[h],c,d,e);else(d=Ba(d)?!!d.capture:!!d,c=ac(c),a&&a[Qb])?(a=a.i,b=String(b).toString(),b in a.g&&(h=a.g[b],c=Vb(h,c,d,e),-1<c&&(Tb(h[c]),Array.prototype.splice.call(h,c,1),0==h.length&&(delete a.g[b],a.h--)))):a&&(a=bc(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Vb(b,c,d,e)),(c=-1<a?b[a]:null)&&"number"!==typeof c&&c&&!c.L&&((e=c.src)&&e[Qb]?Wb(e.i,c):(d=c.type,b=c.proxy,e.removeEventListener?e.removeEventListener(d,b,c.capture):
e.detachEvent?e.detachEvent(d in Yb?Yb[d]:Yb[d]="on"+d,b):e.addListener&&e.removeListener&&e.removeListener(b),Zb--,(d=bc(e))?(Wb(d,c),0==d.h&&(d.src=null,e[Xb]=null)):Tb(c))))}function bc(a){a=a[Xb];return a instanceof Ub?a:null}var cc="__closure_events_fn_"+(1E9*Math.random()>>>0);function ac(a){if("function"===typeof a)return a;a[cc]||(a[cc]=function(b){return a.handleEvent(b)});return a[cc]};function T(){S.call(this);this.i=new Ub(this);this.W=this;this.I=null}Ea(T,S);T.prototype[Qb]=!0;T.prototype.removeEventListener=function(a,b,c,d){$b(this,a,b,c,d)};
function U(a,b){var c=a.I;if(c){var d=[];for(var e=1;c;c=c.I)d.push(c),++e}a=a.W;c=b.type||b;"string"===typeof b?b=new Pb(b,a):b instanceof Pb?b.target=b.target||a:(e=b,b=new Pb(c,a),Db(b,e));e=!0;if(d)for(var h=d.length-1;0<=h;h--){var f=b.g=d[h];e=dc(f,c,!0,b)&&e}f=b.g=a;e=dc(f,c,!0,b)&&e;e=dc(f,c,!1,b)&&e;if(d)for(h=0;h<d.length;h++)f=b.g=d[h],e=dc(f,c,!1,b)&&e}
T.prototype.J=function(){T.S.J.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Tb(d[e]);delete a.g[c];a.h--}}this.I=null};function dc(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.L&&f.capture==c){var g=f.listener,k=f.P||f.src;f.O&&Wb(a.i,f);e=!1!==g.call(k,d)&&e}}return e&&!d.defaultPrevented};function ec(a){try{return C.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function fc(){}fc.prototype.g=null;function gc(a){var b;(b=a.g)||(b={},hc(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b};var ic;function jc(){}Ea(jc,fc);function kc(a){return(a=hc(a))?new ActiveXObject(a):new XMLHttpRequest}function hc(a){if(!a.h&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.h=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.h}ic=new jc;function lc(a,b,c){if("function"===typeof a)c&&(a=D(a,c));else if(a&&"function"==typeof a.handleEvent)a=D(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:C.setTimeout(a,b||0)};var mc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function nc(a){T.call(this);this.headers=new Map;this.B=a||null;this.h=!1;this.D=this.g=null;this.H="";this.j=this.G=this.s=this.F=!1;this.C=0;this.A=null;this.T="";this.M=this.N=!1}Ea(nc,T);var oc=/^https?$/i,pc=["POST","PUT"],qc=[];function rc(a,b){var c=new nc;qc.push(c);b&&c.i.add("complete",b,!1,void 0,void 0);c.i.add("ready",c.X,!0,void 0,void 0);c.C=2E3;c.N=!0;sc(c,a)}n=nc.prototype;n.X=function(){this.l||(this.l=!0,this.J());Ra(qc,this)};
function sc(a,b){var c={};if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.H+"; newUri="+b);a.H=b;a.F=!1;a.h=!0;a.g=a.B?kc(a.B):kc(ic);a.D=a.B?gc(a.B):gc(ic);a.g.onreadystatechange=D(a.U,a);try{a.G=!0,a.g.open("GET",String(b),!0),a.G=!1}catch(h){tc(a);return}b=new Map(a.headers);if(c)if(Object.getPrototypeOf(c)===Object.prototype)for(var d in c)b.set(d,c[d]);else if("function"===typeof c.keys&&"function"===typeof c.get){d=w(c.keys());for(var e=d.next();!e.done;e=d.next())e=
e.value,b.set(e,c.get(e))}else throw Error("Unknown input type for opt_headers: "+String(c));c=Array.from(b.keys()).find(function(h){return"content-type"==h.toLowerCase()});d=C.FormData&&!1;!(0<=Pa(pc,"GET"))||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=w(b);for(c=b.next();!c.done;c=b.next())d=w(c.value),c=d.next().value,d=d.next().value,a.g.setRequestHeader(c,d);a.T&&(a.g.responseType=a.T);"withCredentials"in a.g&&a.g.withCredentials!==a.N&&(a.g.withCredentials=
a.N);try{uc(a),0<a.C&&(a.M=vc(a.g),a.M?(a.g.timeout=a.C,a.g.ontimeout=D(a.V,a)):a.A=lc(a.V,a.C,a)),a.s=!0,a.g.send(""),a.s=!1}catch(h){tc(a)}}function vc(a){return Ta&&"number"===typeof a.timeout&&void 0!==a.ontimeout}n.V=function(){"undefined"!=typeof xa&&this.g&&(U(this,"timeout"),this.abort(8))};function tc(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);wc(a);xc(a)}function wc(a){a.F||(a.F=!0,U(a,"complete"),U(a,"error"))}
n.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,U(this,"complete"),U(this,"abort"),xc(this))};n.J=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),xc(this,!0));nc.S.J.call(this)};n.U=function(){this.isDisposed()||(this.G||this.s||this.j?yc(this):this.ba())};n.ba=function(){yc(this)};
function yc(a){if(a.h&&"undefined"!=typeof xa&&(!a.D[1]||4!=(a.g?a.g.readyState:0)||2!=zc(a)))if(a.s&&4==(a.g?a.g.readyState:0))lc(a.U,0,a);else if(U(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.h=!1;try{var b=zc(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var h=String(a.H).match(mc)[1]||null;!h&&C.self&&C.self.location&&(h=C.self.location.protocol.slice(0,-1));e=!oc.test(h?h.toLowerCase():"")}d=
e}d?(U(a,"complete"),U(a,"success")):wc(a)}finally{xc(a)}}}function xc(a,b){if(a.g){uc(a);var c=a.g,d=a.D[0]?function(){}:null;a.g=null;a.D=null;b||U(a,"ready");try{c.onreadystatechange=d}catch(e){}}}function uc(a){a.g&&a.M&&(a.g.ontimeout=null);a.A&&(C.clearTimeout(a.A),a.A=null)}n.isActive=function(){return!!this.g};function zc(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Ac;try{new URL("s://g"),Ac=!0}catch(a){Ac=!1}var Bc=Ac;function Cc(a){var b=ua.apply(1,arguments);if(0===b.length)return Hb(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Hb(c)};function Dc(a){this.aa=a}function V(a){return new Dc(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Ec=[V("data"),V("http"),V("https"),V("mailto"),V("ftp"),new Dc(function(a){return/^[^:]*([/?#]|$)/.test(a)})];function Fc(a){var b=void 0===b?Ec:b;a:{b=void 0===b?Ec:b;for(var c=0;c<b.length;++c){var d=b[c];if(d instanceof Dc&&d.aa(a)){a=new R(a,Ib);break a}}a=void 0}return a||Jb};function Gc(a,b){a.src=b instanceof Fb&&b.constructor===Fb?b.g:"type_error:TrustedResourceUrl";var c,d;(c=(b=null==(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};function Hc(a,b){if(b instanceof R)b=b instanceof R&&b.constructor===R?b.g:"type_error:SafeUrl";else{b:if(Bc){try{var c=new URL(b)}catch(d){c="https:";break b}c=c.protocol}else c:{c=document.createElement("a");try{c.href=b}catch(d){c=void 0;break c}c=c.protocol;c=":"===c||""===c?"https:":c}b="javascript:"!==c?b:void 0}void 0!==b&&a.open(b,void 0,void 0)};function W(a){this.o=qb(a)}la(W,Q);n=W.prototype;n.getEnableSsEngine=function(){return P(this,2)};n.getEnableAwr=function(){return P(this,3)};n.getEnableHelpSuggestions=function(){return P(this,4)};n.getAlohaAutoGaRollout=function(){return P(this,5)};n.getEnableConfigurator=function(){return P(this,6)};n.getEnableMweb=function(){return P(this,7)};n.getEnableCtlConsentCheckbox=function(){return P(this,8)};n.getEnableIframe=function(){return P(this,9)};
n.getEnableScreenshotNudge=function(){return P(this,10)};n.getEnableWebStartupConfigEndpoint=function(){return P(this,11)};n.getEnableJunkNudge=function(){return P(this,12)};n.getEnableConfiguratorLocale=function(){return P(this,13)};n.getEnableTinyNoPointer=function(){return P(this,14)};n.getEnableSupportSessionLogging=function(){return P(this,15)};n.getEnableFileUploadForScreenshot=function(){return P(this,16)};n.getEnableDirectDeflectionForSingleCategory=function(){return P(this,17)};
n.getEnableImageSanitization=function(){return P(this,18)};n.getEnableAlohaBinarySplit=function(){return P(this,19)};n.getEnableDbFeedbackIntents=function(){return P(this,20)};n.getEnableMarkMandatoryFieldsWithRequired=function(){return P(this,21)};n.getEnableFeedbackCategoryCustomUi=function(){return P(this,22)};n.getEnableRealtimeCtl=function(){return P(this,23)};function Ic(a){this.o=qb(a)}la(Ic,Q);function Jc(a){return Kc.some(function(b){return b.test(a)})}var Kc=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/inapp/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var Lc="af;am;ar-EG;ar-JO;ar-MA;ar-SA;ar-XB;ar;az;be;bg;bn;bs;ca;cs;cy;da;de-AT;de-CH;de;el;en;en-GB;en-AU;en-CA;en-IE;en-IN;en-NZ;en-SG;en-XA;en-XC;en-ZA;es;es-419;es-AR;es-BO;es-CL;es-CO;es-CR;es-DO;es-EC;es-GT;es-HN;es-MX;es-NI;es-PA;es-PE;es-PR;es-PY;es-SV;es-US;es-UY;es-VE;et;eu;fa;fi;fil;fr-CA;fr-CH;fr;gl;gsw;gu;he;hi;hr;hu;hy;id;in;is;it;iw;ja;ka;kk;km;kn;ko;ky;ln;lo;lt;lv;mk;ml;mn;mo;mr;ms;my;nb;ne;nl;no;pa;pl;pt;pt-BR;pt-PT;ro;ru;si;sk;sl;sq;sr-Latn;sr;sv;sw;ta;te;th;tl;tr;uk ; ur ; uz ; vi ; zh;zh-CN;zh-HK;zh-TW;zu".split(";");
function Mc(a){var b;return null==(b=a.formContent)?void 0:b.locale};var Nc=da(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_light_binary.js"]),Oc=da(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);function Pc(a,b){var c=Mc(a);c=(c&&Lc.includes(c)?Mc(a):"en").replaceAll("-","_").toLowerCase();var d;a=(null==(d=a.initializationData)?0:d.useNightlyRelease)?"nightly":"live";var e;return(null==b?0:null==(e=b.getEnableAlohaBinarySplit)?0:e.call(b))?Cc(Nc,a):Cc(Oc,a,c)};var Qc,Rc;function Sc(a,b,c,d){if(Qc)return Qc;var e=Pc(a,d);return Qc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Nb(document);Gc(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+e.toString())};c.body.appendChild(g)})}
function Tc(a,b,c,d){if(Rc)return Rc;var e=Pc(a,d);return Rc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Nb(document);Gc(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+e.toString())};c.body.appendChild(g)})}
function Uc(a,b,c,d,e){e=void 0===e?!0:e;var h,f,g,k,l;return A(function(m){switch(m.g){case 1:return h=Date.now(),y(m,Sc(a,c,d,b),2);case 2:f=m.i;if(!(e||(null==(k=a.initializationData)?0:k.useNightlyRelease)||(null==(l=a.initializationData)?0:l.isLocalServer))){g=f.initializeFeedbackClient(a,h,b);m.g=3;break}return y(m,f.initializeFeedbackClientAsync(a,h,b),4);case 4:g=m.i;case 3:return g.initiateAloha(),m.return(g)}})}
function Vc(a,b,c,d){var e,h,f;return A(function(g){if(1==g.g)return e=Date.now(),y(g,Tc(a,c,d.document,b),2);if(3!=g.g)return h=g.i,y(g,h.initializeFeedbackClientAsync(a,e,b,d),3);f=g.i;f.initiateAloha();return g.return(f)})}
function Wc(a,b,c){var d=!0;d=void 0===d?!0:d;var e,h,f,g,k,l,m,q,p,v;return A(function(J){e=c||C;if(null==(h=b)?0:null==(g=(f=h).getEnableAlohaBinarySplit)?0:g.call(f)){k=e;if(k.isFormOpened)throw l=Error("Form is either loading or already opened"),l.name="DuplicateFormError",l;k.isFormOpened=!0;a.callbacks=a.callbacks||{};m=a.callbacks.onClose||function(){};a.callbacks.onClose=function(x){k.isFormOpened=!1;m(x)};try{return J.return(Vc(a,b,k,e))}catch(x){throw k.isFormOpened=!1,x;}}else{q=e;if(q.isFormOpened)throw p=
Error("Form is either loading or already opened"),p.name="DuplicateFormError",p;q.isFormOpened=!0;a.callbacks=a.callbacks||{};v=a.callbacks.onClose||function(){};a.callbacks.onClose=function(x){q.isFormOpened=!1;v(x)};try{return J.return(Uc(a,b,q,e.document,d))}catch(x){throw q.isFormOpened=!1,x;}}})};function Xc(a,b){return A(function(c){return c.return(new Promise(function(d){var e=Yc(null!=b?b:"")+"/aloha_form_properties?productId="+a;rc(e,function(h){var f=h.target;h=null;try{var g=JSON,k=g.stringify;if(f.g){var l=f.g.responseText;0==l.indexOf(")]}'\n")&&(l=l.substring(5));b:{if(C.JSON)try{var m=C.JSON.parse(l);break b}catch(v){}m=ec(l)}}else m=void 0;var q=k.call(g,m);if(null==q||""==q)h=new Ic;else{var p=JSON.parse(q);if(!Array.isArray(p))throw Error(void 0);fb(p,16);h=pb(Ic,p)}}catch(v){k=
new Ic;m=new W;m=O(m,5,!0);m=O(m,2,!0);m=O(m,4,!1);m=O(m,8,!0);m=O(m,9,!0);m=O(m,7,!0);m=O(m,10,!0);m=O(m,12,!0);m=O(m,13,!1);m=O(m,14,!0);m=O(m,15,!0);m=O(m,20,!1);if(null!=m){if(!(m instanceof W))throw Error("Expected instanceof "+nb(W)+" but got "+(m&&nb(m.constructor)));}else m=void 0;q=k.o;p=L(q);if(p&2)throw Error();Ab(q,p,1,m);h=k}d(h)})}))})}function Yc(a){return Jc(a)?a:"https://www.google.com/tools/feedback"};function Zc(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||C,e=d.document,h=a.nonce||Lb(d);h&&!a.nonce&&(a.nonce=h);if("help"==a.flow){var f=ya("document.location.href",d);!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;if(b&&JSON&&JSON.stringify){var g=JSON.stringify(b);(f=1200>=g.length)&&(a.psdJson=g)}f||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(f=d.GOOGLE_FEEDBACK_START)f.apply(d,
b);else{d=c+"/load.js?";for(var k in a)b=a[k],null==b||Ba(b)||(d+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=e?new Ob(9==e.nodeType?e:e.ownerDocument||e.document):Ga||(Ga=new Ob);a=Nb(a.g);h&&a.setAttribute("nonce",h);h=Hb(d);Gc(a,h);e.body.appendChild(a)}}
function $c(a,b,c,d){var e,h;A(function(f){e=c||C;var g=["web_answers"].includes(a.triggerId)?"en":a.locale,k="DEV"===a.serverEnvironment,l=c||C;l=a.nonce||Lb(l);g={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket,triggerId:a.triggerId},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:g,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,
oa:void 0,defaultFormInputValues:void 0,defaultFormInputValuesString:void 0,abuseLink:a.abuseLink},initializationData:{isLocalServer:k,nonce:l,useNightlyRelease:k,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,
enableAnonymousFeedback:a.enableAnonymousFeedback}};b&&(k=new Map(Object.entries(b)),g.extraData.productSpecificData=k);h=g;return y(f,Wc(h,d,e),0)})}
function ad(a,b,c){try{if("help"===a.flow){var d=a.helpCenterPath.replace(/^\//,"");Hc(c||window,Fc("https://support.google.com/"+d))}else"submit"===a.flow?Zc(a,b,c):Xc(a.productId,a.feedbackServerUri).then(function(e){var h=void 0===h?!1:h;var f=e.o;var g=L(f),k=zb(f,g,1,h);var l=!1;if(null==k||"object"!==typeof k||(l=Array.isArray(k))||k.R!==lb)if(l){var m=l=I(k);0===m&&(m|=g&16);m|=g&2;m!==l&&K(k,m);l=new W(k)}else l=void 0;else l=k;l!==k&&null!=l&&Ab(f,g,1,l,h);f=l;null!=f&&(e=e.o,g=L(e),g&2||
(k=f,l=k.o,m=L(l),k=m&2?yb(k,l,m,!1):k,k!==f&&(f=k,Ab(e,g,1,f,h))));h=f;e=!Ua||(null==h?void 0:h.getEnableMweb());f=!a.tinyNoPointer||(null==h?void 0:h.getEnableTinyNoPointer());!h||h.getAlohaAutoGaRollout()&&e&&f?$c(a,b,c,h):Zc(a,b,c)},function(e){e&&"DuplicateFormError"!==e.name&&Zc(a,b,c)})}catch(e){$c(a,b,c,null)}}var X=["userfeedback","api","startFeedback"],Y=C;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===ad?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=ad;}).call(this);
