import {
    HorizontalBox, Button, VerticalBox,
    GroupBox, ListView, CheckBox,
    ScrollView, StandardListView,
    StandardButton, TextEdit
} from "std-widgets.slint";
import { activity-status, importance, connection-status } from "./generated.slint";
import { PCaller, Person, PAction, Types } from "./types.slint";
import { HNScrollView, HNScrollViewHorizontal } from "./ScrollView.slint";
import { Theme } from "./theme.slint";
import { HereNowScreenShareSelectorInner, ScreenShareGroup } from "./screen-share/screen-share-selector-inner.slint";
import { HereNowPeopleListInner } from "./people-list/people-list-inner.slint";
import { HereNowActiveCallInner } from "./active-call/active-call-inner.slint";
import { DraggableWindow } from "draggable_window.slint";

// https://slint-ui.com/releases/1.0.2/docs/rust/slint/docs/debugging_techniques/index.html

export component HereNowMainWindow inherits DraggableWindow {
    in property <bool> keep-on-top: true;
    always-on-top: self.keep-on-top;
    min-width: 120px;
    title: "Here Now";
    icon: Theme.app-icon;
    // Slint on winit has an even-odd rendering bug with loading fonts from Google Webfonts...
    // default-font-family: "Montserrat";
    default-font-weight: 400;

    callback show-settings();
    callback close();

    VerticalLayout {
        spacing: 20px;
        alignment: start;

        VerticalLayout {
            Button {
                text: "Settings";
                height: 30px;
                width: 130px;
                clicked => { root.show-settings(); }
            }
            Button {
                text: "Close";
                height: 30px;
                width: 130px;
                clicked => { root.close(); }
            }
        }
    }
}
