import {
    HorizontalBox, Button, VerticalBox,
    GroupBox, ListView, CheckBox,
    ScrollView, StandardListView,
    StandardButton, TextEdit
} from "std-widgets.slint";
import { Theme } from "./theme.slint";
import { DraggableWindow } from "draggable_window.slint";
import { HnToggle } from "elements/hn-toggle.slint";
import { HnTextHeading } from "elements/hn-text-heading.slint";
import { HnButton } from "elements/hn-button.slint";
import { HnContainer } from "elements/hn-container.slint";

// https://slint-ui.com/releases/1.0.2/docs/rust/slint/docs/debugging_techniques/index.html

export struct ProfileServer {
    uid: string,
    label: string,
    url: string,
}

export struct Profile {
    uid: string,
    label: string,
    enabled: bool,
    servers: [ProfileServer],
}

export component HereNowMainWindow inherits DraggableWindow {
    in property <bool> keep-on-top: true;
    always-on-top: self.keep-on-top;
    min-width: 220px;
    title: "Here Now";
    icon: Theme.app-icon;
    // Slint on winit has an even-odd rendering bug with loading fonts from Google Webfonts...
    // default-font-family: "Montserrat";
    default-font-weight: 400;

    callback show-profile-settings(string);
    callback toggle-profile(string);
    callback close();

    in property <[Profile]> profiles: [
        { uid: "pfl_cjhsotnabhossbcdj9n0", enabled: true, label: "Default", servers: [
            { uid: "psrv_cjhsp7nabhostmpr044g", label: "Covalent Server", url: "https://herenow.covalent.team" },
            { uid: "psrv_cjhsp7vabhostmpr045g", label: "Local Server", url: "http://localhost:9000" },
        ] },
        { uid: "pfl_cjhsotfabhossbcdj9mg", enabled: false, label: "Test Profile", servers: [
            { uid: "psrv_cjhsp87abhostmpr046g", label: "Covalent Server", url: "https://herenow.covalent.team" },
        ] },
    ];

    HnContainer {
        background: Theme.background-body;
        for profile in root.profiles: VerticalLayout {
            HorizontalLayout {
                spacing: Theme.spaceX;
                VerticalLayout {
                    alignment: center;
                    HnToggle {
                        horizontal-stretch: 0;
                        confirmed-enabled: profile.enabled;
                        toggle => { root.toggle-profile(profile.uid); }
                    }
                }
                VerticalLayout {
                    alignment: center;
                    HnTextHeading {
                        resize: 0.8;
                        horizontal-stretch: 1;
                        text: profile.label;
                        color: profile.enabled ? Theme.in-call-color : Theme.text-body.brighter(3);
                    }
                }
                VerticalLayout {
                    alignment: center;
                    HnButton {
                        text: "⚙️";
                        clicked => { root.show-profile-settings(profile.uid); }
                    }
                }
            }
        }
        HnButton {
            text: "Close";
            height: 30px;
            width: 130px;
            clicked => { root.close(); }
        }
    }
}
