import { Theme } from "./theme.slint";
import { HnAppIcon } from "elements/hn-app-icon.slint";
import { HnTextHeading } from "elements/hn-text-heading.slint";
import { HnButton } from "elements/hn-button.slint";

export struct Notification {
    key: string,
    title: string,
    body: string,
}

export component HnModalHeading inherits HorizontalLayout {
    in property <string> title: "Modal Heading Title";
    VerticalLayout {
        alignment: center;
        HnAppIcon { size: 32px; }
    }
    VerticalLayout {
        alignment: center;
        padding-top: 5px;
        HnTextHeading { text: root.title; }
    }
}

export component HnNotification inherits Rectangle {
    in property <Notification> notification;
    callback dismiss();
    // warning colors
    border-color: Theme.text-body;
    border-width: 1px;
    border-radius: 3px;

    HorizontalLayout {
        padding: 12px;
        VerticalLayout {
            horizontal-stretch: 1;
            Text {
                text: notification.title;
                color: Theme.text-body;
                font-family: Theme.text-ui-label-family;
                font-size: Theme.text-ui-label-size;
                font-weight: Theme.text-ui-label-weight;
            }
            Text {
                text: notification.body;
                color: Theme.text-body;
                font-family: Theme.text-content-family;
                font-size: Theme.text-content-size;
                font-weight: Theme.text-content-weight;
            }
        }
        VerticalLayout {
            horizontal-stretch: 0;
            alignment: start;
            HnButton {
                text: "Dismiss";
                clicked => {
                    root.dismiss();
                }
            }
        }
    }       
}
