// Consider: Generating our own md from tailwind / generator stuff we've previously built
// See https://github.com/slint-ui/slint/blob/7b26d6e58f9f98d15042445a6671b599685457d6/internal/compiler/widgets/material-base/md.slint
export global Theme {
    in-out property <length> spaceX: 8px;
    in-out property <length> spaceY: 8px;
    in-out property <length> radius-window: 4px;
    in-out property <length> text-ui-heading-size: 24px;
    in-out property <string> text-ui-heading-family: "Inter";
    in-out property <int> text-ui-heading-weight: 600;
    in-out property <length> text-content-size: 13px;
    in-out property <string> text-content-family: "Inter";
    in-out property <int> text-content-weight: 400;
    in-out property <string> text-ui-label-family: "Inter";
    in-out property <length> text-ui-label-size: 16px;
    in-out property <int> text-ui-label-weight: 600;
    in-out property <string> text-ui-button-family: "Inter";
    in-out property <length> text-ui-button-size: 13px;
    in-out property <int> text-ui-button-weight: 500;
    in-out property <string> text-ui-input-family: "Inter";
    in-out property <length> text-ui-input-size: 14px;
    in-out property <int> text-ui-input-weight: 400;
    in-out property <color> text-ui-input-inactive-border: #D9D9D9;
    in-out property <color> text-ui-input-active-border: #074DFF;
    in-out property <image> app-icon: @image-url("./app_icon.png");
    in-out property <image> icon-none: @image-url("./none.png");
    in-out property <color> text-body: #222;
    in-out property <color> background-body: white;
    in-out property <color> background-body-transparent: rgba(255, 255, 255, 0);
    in-out property <color> background-call: rgba(42, 42, 42, 0.9);
    in-out property <color> background-call-transparent: rgba(42, 42, 42, 0);
    in-out property <color> in-call-color: #074DFF;
    // https://cubic-bezier.com/#.53,.01,.53,.99
}
