# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "workspace-hack"

# Format version for hakari's output. Version 4 requires cargo-hakari 0.9.22 or above.
dep-format-version = "4"

# Setting workspace.resolver = "2" in the root Cargo.toml is HIGHLY recommended.
# Hakari works much better with the new feature resolver.
# For more about the new feature resolver, see:
# https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver
resolver = "2"

# Add triples corresponding to platforms commonly used by developers here.
# https://doc.rust-lang.org/rustc/platform-support.html
platforms = [
    # "x86_64-unknown-linux-gnu",
    # "x86_64-apple-darwin",
    # "x86_64-pc-windows-msvc",
]

[final-excludes]
workspace-members = [
    "derive-codegen",
    "devx-cmd",
    "i-codegen-code",
    "i-codegen-derive",
    "i-hn-app-proc",
    "i-hn-desktop-ui-messages-proc",
    "i-hn-server-proc",
    "i-slint-backend-qt",
    "i-slint-backend-selector",
    "i-slint-backend-winit",
    "i-slint-compiler",
    "i-slint-core",
    "i-slint-parser-test-macro",
    "shipyard_app",
    "slint",
    "slint-build",
    "slint-interpreter",
    "slint-viewer",
    "slint-lsp",
]

# Write out exact versions rather than a semver range. (Defaults to false.)
# exact-versions = true
